set names 'utf8';
CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_chats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) DEFAULT NULL,
  `content` text,
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_dailiconfigs` (
  `vkey` varchar(20) NOT NULL,
  `value` text,
  PRIMARY KEY (`vkey`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_kms` (
  `kid` int(11) NOT NULL AUTO_INCREMENT,
  `kind` tinyint(1) NOT NULL DEFAULT '0',
  `daili` int(11) NOT NULL DEFAULT '0',
  `km` varchar(50) NOT NULL,
  `ms` tinyint(2) NOT NULL DEFAULT '1',
  `isuse` tinyint(1) DEFAULT '0',
  `uid` int(11) DEFAULT NULL,
  `usetime` datetime DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`kid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_lqqs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `qq` varchar(255) DEFAULT NULL,
  `zt` tinyint(1) DEFAULT '0',
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_mailcode` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` tinyint(1) DEFAULT '1',
  `uid` int(11) NOT NULL DEFAULT '0',
  `code` varchar(100) NOT NULL,
  `mail` varchar(50) DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  `endtime` datetime DEFAULT NULL,
  `state` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_messages` (
  `mid` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) DEFAULT NULL,
  `fid` int(11) DEFAULT NULL,
  `content` text,
  `isread` tinyint(1) DEFAULT '0',
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`mid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_qds` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) DEFAULT NULL,
  `lx` int(11) DEFAULT NULL COMMENT '1',
  `adddate` date DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_qqs` (
  `qid` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL DEFAULT '0',
  `usedate` datetime DEFAULT NULL,
  `qq` decimal(10,0) NOT NULL,
  `pwd` varchar(80) DEFAULT NULL,
  `sid` varchar(80) NOT NULL,
  `skey` varchar(20) NOT NULL,
  `sidzt` tinyint(1) DEFAULT '0',
  `skeyzt` tinyint(1) DEFAULT '0',
  `pc_p_skey` varchar(50) NOT NULL,
  `cp_p_skey` varchar(50) NOT NULL,
  `qqzt` tinyint(1) NOT NULL DEFAULT '0',
  `iszan` tinyint(1) DEFAULT '0',
  `zanrate` int(3) DEFAULT '15',
  `zannet` tinyint(1) DEFAULT '0',
  `lastzan` datetime DEFAULT NULL,
  `nextzan` datetime DEFAULT NULL,
  `isreply` tinyint(1) DEFAULT '0',
  `replycon` text,
  `replypic` varchar(1000) DEFAULT NULL,
  `replyrate` int(3) DEFAULT '15',
  `replynet` tinyint(1) DEFAULT '0',
  `lastreply` datetime DEFAULT NULL,
  `nextreply` datetime DEFAULT NULL,
  `isshuo` tinyint(1) DEFAULT '0',
  `shuotype` tinyint(1) DEFAULT '0',
  `shuorate` int(3) DEFAULT '30',
  `shuonet` tinyint(1) DEFAULT '0',
  `shuoshuo` text,
  `shuopic` text,
  `shuophone` text NOT NULL,
  `lastshuo` datetime DEFAULT NULL,
  `nextshuo` datetime DEFAULT NULL,
  `isdelshuo` tinyint(1) DEFAULT '0',
  `delshuonet` tinyint(1) DEFAULT '0',
  `lastdelshuo` datetime DEFAULT NULL,
  `nextdelshuo` datetime DEFAULT NULL,
  `isqd` tinyint(1) DEFAULT NULL,
  `qdcon` text,
  `qdnet` tinyint(1) DEFAULT '0',
  `lastqd` datetime DEFAULT NULL,
  `nextqd` datetime DEFAULT NULL,
  `is3gqq` tinyint(1) DEFAULT '0',
  `3gqqnet` tinyint(1) DEFAULT '0',
  `last3gqq` datetime DEFAULT NULL,
  `next3gqq` datetime DEFAULT NULL,
  `isly` tinyint(1) NOT NULL DEFAULT '0',
  `lycon` text,
  `lastly` datetime DEFAULT NULL,
  `nextly` datetime DEFAULT NULL,
  `isfw` tinyint(1) NOT NULL DEFAULT '0',
  `lastfw` datetime DEFAULT NULL,
  `nextfw` datetime DEFAULT NULL,
  `isvipqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastvipqd` datetime DEFAULT NULL,
  `nextvipqd` datetime DEFAULT NULL,
  `iszyzan` tinyint(1) NOT NULL DEFAULT '0',
  `lastzyzan` datetime DEFAULT NULL,
  `nextzyzan` datetime DEFAULT NULL,
  `iszf` tinyint(4) NOT NULL DEFAULT '0',
  `zfok` text NOT NULL,
  `zfcon` text NOT NULL,
  `zfrate` tinyint(1) NOT NULL DEFAULT '15',
  `zfnet` tinyint(1) NOT NULL DEFAULT '0',
  `lastzf` datetime DEFAULT NULL,
  `nextzf` datetime DEFAULT NULL,
  `isht` tinyint(1) NOT NULL DEFAULT '0',
  `lastht` datetime DEFAULT NULL,
  `nextht` datetime DEFAULT NULL,
  `ists` tinyint(1) NOT NULL DEFAULT '0',
  `lastts` datetime DEFAULT NULL,
  `nextts` datetime DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  `islz` tinyint(4) NOT NULL DEFAULT '0',
  `lastlz` datetime DEFAULT NULL,
  `nextlz` datetime DEFAULT NULL,
  `isqb` tinyint(4) NOT NULL DEFAULT '0',
  `lastqb` datetime DEFAULT NULL,
  `nextqb` datetime DEFAULT NULL,
  `isqt` tinyint(1) NOT NULL DEFAULT '0',
  `lastqt` datetime DEFAULT NULL,
  `nextqt` datetime DEFAULT NULL,
  `islw` tinyint(4) NOT NULL DEFAULT '0',
  `lastlw` datetime DEFAULT NULL,
  `nextlw` datetime DEFAULT NULL,
  `isauto` tinyint(4) NOT NULL DEFAULT '1',
  `lastauto` datetime DEFAULT NULL,
  `qqlast` datetime DEFAULT NULL,
  `qqnext` datetime DEFAULT NULL,
  `isgcw` tinyint(1) NOT NULL DEFAULT '0',
  `lastgcw` datetime DEFAULT NULL,
  `nextgcw` datetime DEFAULT NULL,
  `iscqqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastcqqd` datetime DEFAULT NULL,
  `nextcqqd` datetime DEFAULT NULL,
  `ismcqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastmcqd` datetime DEFAULT NULL,
  `nextmcqd` datetime DEFAULT NULL,
  `isgamevipqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastgamevipqd` datetime DEFAULT NULL,
  `nextgamevipqd` datetime DEFAULT NULL,
  `isqunqd` tinyint(1) NOT NULL,
  `qunqdcon` text,
  `lastqunqd` datetime DEFAULT NULL,
  `nextqunqd` datetime DEFAULT NULL,
  `isdelll` tinyint(1) NOT NULL,
  `lastdelll` datetime DEFAULT NULL,
  `nextdelll` datetime DEFAULT NULL,
  `iscfqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastcfqd` datetime DEFAULT NULL,
  `nextcfqd` datetime DEFAULT NULL,
  `isqunwenwenqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastqunwenwenqd` datetime DEFAULT NULL,
  `nextqunwenwenqd` datetime DEFAULT NULL,
  `isyqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastyqd` datetime DEFAULT NULL,
  `nextyqd` datetime DEFAULT NULL,
  `isdldqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastdldqd` datetime DEFAULT NULL,
  `nextdldqd` datetime DEFAULT NULL,
  `isweiyunqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastweiyunqd` datetime DEFAULT NULL,
  `nextweiyunqd` datetime DEFAULT NULL,
  `isfzqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastfzqd` datetime DEFAULT NULL,
  `nextfzqd` datetime DEFAULT NULL,
  `isvideoqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastvideoqd` datetime DEFAULT NULL,
  `nextvideoqd` datetime DEFAULT NULL,
  `isnianvipcj` tinyint(1) NOT NULL DEFAULT '0',
  `lastnianvipcj` datetime DEFAULT NULL,
  `nextnianvipcj` datetime DEFAULT NULL,
  `isqqgjqd` tinyint(1) NOT NULL DEFAULT '0',
  `lastqqgjqd` datetime DEFAULT NULL,
  `nextqqgjqd` datetime DEFAULT NULL,
  `isqd3366` tinyint(1) NOT NULL DEFAULT '0',
  `lastqd3366` datetime DEFAULT NULL,
  `nextqd3366` datetime DEFAULT NULL,
  `islld` tinyint(1) NOT NULL DEFAULT '0',
  `lastlld` datetime DEFAULT NULL,
  `nextlld` datetime DEFAULT NULL,
  PRIMARY KEY (`qid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_qqz` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uin` varchar(255) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_quanrens` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uin` varchar(255) DEFAULT NULL,
  `albumid` varchar(255) DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_users` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `user` varchar(255) NOT NULL,
  `daili` tinyint(1) NOT NULL DEFAULT '0',
  `vip` tinyint(1) DEFAULT '0',
  `vipstart` date DEFAULT NULL,
  `vipend` date DEFAULT NULL,
  `rmb` int(5) NOT NULL DEFAULT '0',
  `jf` int(11) NOT NULL DEFAULT '0',
  `peie` tinyint(2) DEFAULT '1',
  `pwd` varchar(40) NOT NULL,
  `sid` varchar(50) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '0',
  `login` tinyint(255) DEFAULT '1',
  `mail` varchar(100) DEFAULT NULL,
  `qq` decimal(12,0) DEFAULT NULL,
  `phone` decimal(12,0) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `regip` varchar(50) DEFAULT NULL,
  `lastip` varchar(50) DEFAULT NULL,
  `regtime` datetime DEFAULT NULL,
  `lasttime` datetime DEFAULT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_webconfigs` (
  `vkey` varchar(255) NOT NULL,
  `value` text,
  PRIMARY KEY (`vkey`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `{DB_PREFIX}_webconfigs` (`vkey`, `value`) VALUES
('adminpwd', '1edb01bc79e2ac001fad3948639fdb84'),
('web_name', '微秒赞'),
('web_domain', 'qz-114.com'),
('web_qq', '1126786437'),
('web_index_title', '微秒赞--全网最快最稳定的24小时离线秒赞平台'),
('web_index_keywords', '微秒赞,秒赞,离线秒赞,秒赞平台,24H离线秒赞,24小时离线秒赞,免费秒赞平台,qq秒赞评,秒评,离线秒评,苹果秒赞,ios秒赞'),
('web_index_description', '微秒赞，全网唯一最稳定秒赞平台！不免费，但绝不欺骗用户！添加QQ设置好就可关掉网页，服务器24小时不间断的为您刷新QQ空间最新说说动态，秒赞每条说说。支持苹果IOS系统和安卓Android系统'),
('regactive', '0'),
('regpeie', '1'),
('regrmb', '0'),
('gonggao_welcome', '欢迎使用微秒赞！'),
('gonggao_index_bottom', ''),
('gonggao_user', '<p style="padding: 8px; font-size: 80%; background-color: #FF1493;">本站唯一域名：qz-114.com</p>\r\n<p style="padding: 7px; font-size: 80%; background-color: #FFFF00;">VIP价格表：5元/月 | 14元/季 | 26元/半年 | 50元/年 | 100元/永久</p>\r\n<p style="padding: 8px; font-size: 80%; background-color: #7CFC00;">本站代理价格为100元,拿卡5折(赠送代理后台,可自助生成卡密)</p>\r\n<p style="padding: 8px; font-size: 80%; background-color: #C6E2FF;">平台分站搭建月付70元,包回本(高配腾讯云+软件监控)</p>\r\n<p style="padding: 8px; font-size: 80%; background-color: #CD6600;">秒赞官方群：<a target="_blank" href="http:///">暂不开放</a> | 本站付费售后群：<a target="_blank" href="http:///">暂不开放</a></p>\r\n<p style="padding: 7px; font-size: 80%; background-color: #FFE1FF;">购买方式：<a target="_blank" href="http:///">暂不开放</a> | <a target="_blank" href="/pay">在线支付宝购卡</a> | <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=1126786437&site=qq&menu=yes">联系客服</a></p>\r\n<img src="http://qzonestyle.gtimg.cn/qzone/vas/opensns/res/img/tengxunyunanquanrenzheng-02.png" border="0" onmouseover="this.src="http://i3.tietuku.com/b0d10d856a0be403.png"" onmouseout="this.src="http://qzonestyle.gtimg.cn/qzone/vas/opensns/res/img/tengxunyunanquanrenzheng-02.png""/>\r\n<a href="http://webscan.360.cn/index/checkwebsite/url/svip.qqmzp.com"><img border="0" src="http://img.webscan.360.cn/status/pai/hash/b13362f39d8e457b93c0ae1858d23c52"/></a>\r\n<div class="list-group-item red"><span>更多功能还在添加中！</span></div>\r\n<a href="qd.html" class="list-group-item red"><span>【火】[热门活动]每日签到送VIP</span></a>'),
('gonggao_daili', '<div class="list-group-item red"><span>我们将证明你的选择是正确的！</span></div>'),
('gonggao_add', '<div class="list-group-item reed"><span>购买配额能添加更多QQ!</span></div>'),
('gonggao_shop', '<div class="list-group-item reed"><span>输入卡密自助开通服务！</span></div>'),
('gonggao_qiandao', '<div class="list-group-item reed"><span>签到即送VIP，名额有限，先到先得！</span></div>\r\n<div class="list-group-item reed"><span>签到会利用添加的QQ发送一条带广告说说，不同意请勿签到！</span></div>'),
('do', 'csmail'),
('web_mb', 'default'),
('web_web_indexmb', 'index1'),
('web_wap_indexmb', 'index'),
('mail_host', 'smtp.qq.com'),
('mail_port', '25'),
('mail_user', 'service@qqmzp.com'),
('mail_pass', 'password'),
('cronrand', '10310'),
('crontype', '0'),
('qd_getvip', '1'),
('qd_num', '1'),
('qd_shuoshuo', '要秒赞就到微秒赞，用了好用我才推荐的！网站qz-114.com！'),
('qd_shuopic', ''),
('qd_shuophone', '微秒赞qz-114.com'),
('price_daili_1vip', '5'),
('price_daili_3vip', '14'),
('price_daili_6vip', '26'),
('price_daili_12vip', '50'),
('price_daili_0vip', '100'),
('price_daili_1peie', '15'),
('price_daili_3peie', '30'),
('price_daili_5peie', '45'),
('price_daili_10peie', '88'),
('netnum', '25'),
('zannet', '10'),
('qd_rule', '1'),
('qqtx_open', '1'),
('qqtx_getvip', '0'),
('qqtx_viptj', '恭喜您！您已成功在微秒赞添加了QQ！'),
('qqtx_vipgx', '恭喜您！您已成功在微秒赞更新了QQ！'),
('qqtx_tj', '【你现在没有开通会员,无法使用功能哦!】\r\n\r\n联系客服1126786437 / 1126786437购买开通VIP！\r\nVIP价格表:5元/月| 14元/季| 26元/半年| 50元/年| 100元/永久\r\n客服不在时，直接转账截图留言，看到信息后会给你发卡密\r\n财付通：客服QQ即为财付通帐号\r\n支付宝：sh@grr.la\r\nQQ红包/转账：支持\r\n微信红包/转账：支持（微信号：izuinb）\r\n支持电信/联通/移动手机话费充值卡\r\n\r\n【恭喜您!您已成功在微秒赞添加了QQ】\r\n\r\n售后群：暂不开放\r\n本消息由微秒赞发送 '),
('qqtx_gx', '【你现在没有开通会员,无法使用功能哦!】\r\n\r\n联系客服1126786437 / 1126786437购买开通VIP！\r\nVIP价格表:5元/月| 14元/季| 26元/半年| 50元/年| 100元/永久\r\n客服不在时，直接转账截图留言，看到信息后会给你发卡密\r\n财付通：客服QQ即为财付通帐号\r\n支付宝：sh@grr.la\r\nQQ红包/转账：支持\r\n微信红包/转账：支持（微信号：izuinb）\r\n支持电信/联通/移动手机话费充值卡\r\n\r\n【恭喜您!您已成功在微秒赞更新了QQ】\r\n\r\n售后群：暂不开放\r\n本消息由微秒赞发送 '),
('web_qun', '');<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_zfdates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uin` varchar(255) DEFAULT NULL,
  `zfuin` varchar(255) DEFAULT NULL,
  `zfdate` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>

CREATE TABLE IF NOT EXISTS `{DB_PREFIX}_zhuanfas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uin` varchar(255) DEFAULT NULL,
  `cellid` varchar(255) DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;<fgf>